name: Update metrics for master branch

on:
  push:
    branches:
      - 'master'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  master_flow:
    name: Master branch update
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        # keys are the same as in build_and_test workflow to make cache available for PRs
        with:
          path: ~/.m2/repository
          key: maven-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-build-
      - name: Run tests
        # we need to run `install` goal here so that gradle will be able to resolve dependencies and run tests on diktat-gradle-plugin
        run: mvn -B install -DskipPluginMarker
      - name: Generate code coverage report
        uses: codecov/codecov-action@v2
        with:
          files: '**/target/site/jacoco*/jacoco.xml,**/reports/jacoco/**/*.xml'
          flags: unittests
          fail_ci_if_error: true # optional (default = false)
